### PR TITLE
Create translation_hu.xml

### PR DESCRIPTION
**Pull request by n0tr3adY**

### CODE REVIEW

**Comment by stijnwop** [comment]
Thanks for the translation! :)

**Comment by n0tr3adY** [comment]
There is only one minor issue with the translation, at input_mouseInteract. The "left" and "right" still in english, and no source to translate this left-right button thing :)

**Comment by stijnwop** [comment]
Yeah, i am using the game translation for that.. so what giants did.
You are playing on Hu? If so, I might want to add those to buttons in the hose system translation files to prevent these things.

**Comment by n0tr3adY** [comment]
Yes, i'm playing on <hu>. That would be very nice thing from you, because old players in my country can't handle english language/text.

**Pull request merged**
